In [1]:
import numpy as np

# Calculate the profite/loss from revenue and expense

In [2]:
revenue = np.array([[180, 200, 220], [24, 36, 40], [12, 28, 20]])
expenses = np.array([[80, 90, 200], [10, 16, 20], [8, 10, 10]])

profite = revenue-expenses
profite

array([[100, 110,  20],
       [ 14,  20,  20],
       [  4,  18,  10]])

# Calculate total sales from units and price per unit using matrix multiplication and using numpy broadcasting

In [3]:
price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30, 40, 50], [5, 10, 15], [2, 5, 7]])
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

# Numpy dot product

In [4]:
np.dot(price_per_unit, units)

array([34400, 50000, 64400])