In [1]:
import numpy as np

In [9]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

# Mean Absolute Error

In [12]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted,y_true):
        total_error += abs(yp-yt)
    print("Total error is:", total_error)
    mae = total_error,len(y_predicted)
    print("Mean Absolute Error is", mae)
    return mae

In [13]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean Absolute Error is (2.5, 5)


(2.5, 5)

# Implement same thing using numpy in much easier way

In [16]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [24]:
np.mean(np.abs(y_predicted, y_true))

0.6

In [19]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [22]:
mae_np(y_predicted, y_true)

0.0

# Implement Log Loss or Binary Cross Entropy

In [25]:
np.log([0])

C:\Users\adnan\AppData\Local\Temp\ipykernel_7668\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [30]:
np.log(1e-15)

-34.538776394910684

In [31]:
epsilon  =1e-15

In [32]:
y_predict

array([1, 1, 0, 0, 1])

In [33]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [34]:
1-epsilon

0.999999999999999

In [36]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted]
y_predicted_new

[0.999999999999999, 0.999999999999999, 0, 0, 0.999999999999999]

In [37]:
y_predicted_new = np.array(y_predicted_new)

In [38]:
np.log(y_predicted_new)

C:\Users\adnan\AppData\Local\Temp\ipykernel_7668\2469092518.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [40]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

C:\Users\adnan\AppData\Local\Temp\ipykernel_7668\1399385479.py:1: RuntimeWarning: divide by zero encountered in log
  np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
C:\Users\adnan\AppData\Local\Temp\ipykernel_7668\1399385479.py:1: RuntimeWarning: invalid value encountered in multiply
  np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


nan

In [43]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [44]:
log_loss(y_true, y_predicted)

9.992007221626415e-16